# Generated by Django 3.0.1 on 2019-12-22 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20191221_1553'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='categories',
        ),
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='blog.Category'),
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(choices=[('currency', 'CURRENCY'), ('banks', 'BANKS'), ('crypto', 'CRYPTO'), ('commodities', 'COMMODITIES')], default='currency', max_length=100),
        ),
    ]
