# Generated by Django 3.0.1 on 2020-01-05 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20200101_1608'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='thumbnail',
            field=models.ImageField(default='images/resource/blackroq_5.jpg', upload_to='Posts %Y%M%d'),
        ),
    ]
