# Generated by Django 3.0.1 on 2020-01-13 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20200110_1038'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='description',
            field=models.TextField(default='The best blog'),
            preserve_default=False,
        ),
    ]
