# Generated by Django 3.0.1 on 2020-01-21 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=100)),
                ('message', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(choices=[('currency', 'CURRENCY'), ('banks', 'BANKS'), ('crypto', 'CRYPTO'), ('commodities', 'COMMODITIES'), ('education', 'EDUCATION'), ('analysis', 'ANALYSIS'), ('news', 'NEWS'), ('faq', 'FAQ')], default='currency', max_length=100),
        ),
    ]
