# Generated by Django 3.0.1 on 2020-01-23 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_auto_20200123_0703'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Faq',
        ),
    ]
