# Generated by Django 3.0.1 on 2020-01-13 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('book', 'Book'), ('course', 'Course')], default='book', max_length=200)),
            ],
            options={
                'verbose_name': 'productcategory',
                'verbose_name_plural': 'productcategories',
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='')),
                ('url', models.URLField()),
                ('category', models.ForeignKey(default='book', on_delete=django.db.models.deletion.CASCADE, related_name='product_categories', to='shop.ProductCategory')),
            ],
        ),
    ]
